apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: environments.platform.ihk.org
spec:
  scope: Namespaced
  group: platform.ihk.org
  names:
    kind: Environment
    plural: environments
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string
                description: "The Azure region to deploy resources in."
                default: "West Europe"
              environment:
                type: object
                description: "Environment metadata configuration."
                properties:
                  owner:
                    type: string
                    description: "The owner of the environment."
                  purpose:
                    type: string
                    description: "The purpose of the environment (e.g., dev, qa)."
                required:
                - owner
                - purpose
              resourceGroup:
                type: object
                description: "Resource group configuration."
                properties:
                  name:
                    type: string
                    description: "Name of the resource group."
                required:
                - name
              aks:
                type: object
                description: "AKS cluster configuration."
                properties:
                  name:
                    type: string
                    description: "Name of the AKS cluster."
                  version:
                    type: string
                    description: "Kubernetes version for AKS."
                    default: "1.30.0"
                  nodeCount:
                    type: integer
                    description: "Number of nodes in the AKS cluster."
                    default: 2
                  nodeImage:
                    type: string
                    description: "The node image to use for AKS nodes."
                    default: "Ubuntu2204"
                  nodeSku:
                    type: string
                    description: "The SKU for AKS nodes."
                    default: "Standard_D2_v2"
                  networkProfile:
                    type: object
                    description: "Network profile for AKS."
                    properties:
                      networkPlugin:
                        type: string
                        description: "Network plugin."
                        default: "azure"
                      networkPolicy:
                        type: string
                        description: "Network policy."
                        default: "azure"
                      serviceCidr:
                        type: string
                        description: "CIDR range for Kubernetes services."
                        default: "10.0.3.0/24"
                      dnsServiceIp:
                        type: string
                        description: "IP address for DNS service."
                        default: "10.0.3.10"
                required:
                - name
                - version
                - nodeCount
                - nodeImage
                - nodeSku
                - networkProfile
              keyVault:
                type: object
                description: "Key Vault configuration."
                properties:
                  name:
                    type: string
                    description: "Name of the Key Vault."
                  sku:
                    type: string
                    description: "SKU for Key Vault."
                    default: "standard"
                required:
                - name
                - sku
              network:
                type: object
                description: "Network configuration."
                properties:
                  vnet:
                    type: object
                    description: "Virtual network configuration."
                    properties:
                      name:
                        type: string
                        description: "Name of the virtual network."
                      addressSpace:
                        type: string
                        description: "Address space for the virtual network."
                    required:
                    - name
                    - addressSpace
                  subnets:
                    type: array
                    description: "List of subnets."
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: "Name of the subnet."
                        addressPrefix:
                          type: string
                          description: "Address prefix for the subnet."
                        purpose:
                          type: string
                          description: "Purpose of the subnet (e.g., aks, database)."
                      required:
                      - name
                      - addressPrefix
                      - purpose
                required:
                - vnet
                - subnets
              database:
                type: object
                description: "Database configuration."
                properties:
                  engine:
                    type: string
                    description: "Database engine (e.g., PostgreSQL)."
                    default: "PostgreSQL"
                  version:
                    type: string
                    description: "Database version."
                    default: "16"
                  sku:
                    type: string
                    description: "Database SKU."
                    default: "B_Gen5_1"
                  storageMb:
                    type: integer
                    description: "Storage size in MB."
                    default: 32768
                  dbName:
                    type: string
                    description: "Name of the database."
                required:
                - engine
                - version
                - sku
                - storageMb
                - dbName
              identity:
                type: object
                description: "Identity configuration for Azure resources."
                properties:
                  subscriptionId:
                    type: string
                    description: "Azure Subscription ID for resources."
                  tenantId:
                    type: string
                    description: "Azure Tenant ID for Key Vault."
                  principalId:
                    type: string
                    description: "Service Principal Object ID for RBAC assignments."
                required:
                - subscriptionId
                - tenantId
                - principalId
            required:
            - region
            - environment
            - resourceGroup
            - aks
            - keyVault
            - network
            - database
            - identity