apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure-environment-composition
spec:
  # must match your XRD apiVersion + kind
  compositeTypeRef:
    apiVersion: platform.ihk.org/v1alpha1
    kind: Environment
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        # The function will return a list of desired resources.
        resources:
          # 1. Resource Group
          - name: resourceGroup
            base:
              apiVersion: azure.m.upbound.io/v1beta1
              kind: ResourceGroup
              spec:
                forProvider:
                  location: "West Europe"
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.resourceGroup.name"
                toFieldPath: "metadata.name"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.resourceGroup.name"
                toFieldPath: "metadata.labels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "metadata.labels[crossplane.io/namespace]"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.owner"
                toFieldPath: "spec.forProvider.tags.owner"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.purpose"
                toFieldPath: "spec.forProvider.tags.purpose"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.region"
                toFieldPath: "spec.forProvider.location"

          # 2. Virtual Network
          - name: virtualNetwork
            base:
              apiVersion: network.azure.m.upbound.io/v1beta1
              kind: VirtualNetwork
              spec:
                forProvider:
                  addressSpace: ["10.0.0.0/16"]
                  resourceGroupNameSelector:
                    matchLabels:
                  location: "West Europe"
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.network.vnet.name"
                toFieldPath: "metadata.name"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.network.vnet.addressSpace"
                toFieldPath: "spec.forProvider.addressSpace[0]"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.region"
                toFieldPath: "spec.forProvider.location"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.network.vnet.name"
                toFieldPath: "metadata.labels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "metadata.labels[crossplane.io/namespace]"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.resourceGroup.name"
                toFieldPath: "spec.forProvider.resourceGroupNameSelector.matchLabels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "spec.forProvider.resourceGroupNameSelector.matchLabels[crossplane.io/namespace]"

          # 3. Subnet for AKS
          - name: subnetAks
            base:
              apiVersion: network.azure.m.upbound.io/v1beta1
              kind: Subnet
              metadata:
              spec:
                forProvider:
                  addressPrefixes: ["10.0.1.0/24"]
                  resourceGroupNameSelector:
                    matchLabels:
                  virtualNetworkNameSelector:
                    matchLabels:
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                  - fromFieldPath: "metadata.name"
                  - fromFieldPath: "spec.network.subnets[0].name"
                  strategy: string
                  string:
                    fmt: "%s-%s"
                toFieldPath: "metadata.name"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.network.subnets[0].addressPrefix"
                toFieldPath: "spec.forProvider.addressPrefixes[0]"
              - type: CombineFromComposite
                combine:
                  variables:
                  - fromFieldPath: "spec.network.vnet.name"
                  - fromFieldPath: "spec.network.subnets[0].name"
                  strategy: string
                  string:
                    fmt: "%s-%s"
                toFieldPath: "metadata.labels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "metadata.labels[crossplane.io/namespace]"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.resourceGroup.name"
                toFieldPath: "spec.forProvider.resourceGroupNameSelector.matchLabels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "spec.forProvider.resourceGroupNameSelector.matchLabels[crossplane.io/namespace]"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.network.vnet.name"
                toFieldPath: "spec.forProvider.virtualNetworkNameSelector.matchLabels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "spec.forProvider.virtualNetworkNameSelector.matchLabels[crossplane.io/namespace]"

          # 3b. Subnet for Database
          - name: subnetDb
            base:
              apiVersion: network.azure.m.upbound.io/v1beta1
              kind: Subnet
              spec:
                forProvider:
                  addressPrefixes: ["10.0.2.0/24"]
                  resourceGroupNameSelector:
                    matchLabels:
                  virtualNetworkNameSelector:
                    matchLabels:
            patches:
              - type: CombineFromComposite
                combine:
                  variables:
                  - fromFieldPath: "metadata.name"
                  - fromFieldPath: "spec.network.subnets[1].name"
                  strategy: string
                  string:
                    fmt: "%s-%s"
                toFieldPath: "metadata.name"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.network.subnets[1].addressPrefix"
                toFieldPath: "spec.forProvider.addressPrefixes[0]"
              - type: CombineFromComposite
                combine:
                  variables:
                  - fromFieldPath: "spec.network.vnet.name"
                  - fromFieldPath: "spec.network.subnets[1].name"
                  strategy: string
                  string:
                    fmt: "%s-%s"
                toFieldPath: "metadata.labels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "metadata.labels[crossplane.io/namespace]"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.resourceGroup.name"
                toFieldPath: "spec.forProvider.resourceGroupNameSelector.matchLabels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "spec.forProvider.resourceGroupNameSelector.matchLabels[crossplane.io/namespace]"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.network.vnet.name"
                toFieldPath: "spec.forProvider.virtualNetworkNameSelector.matchLabels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "spec.forProvider.virtualNetworkNameSelector.matchLabels[crossplane.io/namespace]"

          # 4. AKS Cluster
          - name: aksCluster
            base:
              apiVersion: containerservice.azure.m.upbound.io/v1beta1
              kind: KubernetesCluster
              spec:
                forProvider:
                  defaultNodePool:
                    name: default
                    nodeCount: 2
                    vmSize: Standard_D2_v2
                    osSku: "Ubuntu2204"
                    vnetSubnetIdSelector:
                      matchLabels:
                  dnsPrefix: "aks"
                  identity:
                    type: SystemAssigned
                  location: "West Europe"
                  resourceGroupNameSelector:
                    matchLabels:
                  kubernetesVersion: "1.30.0"
                  networkProfile:
                    networkPlugin: "azure"
                    networkPolicy: "calico"
                  tags:
                    provisioner: crossplane
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.name"
                toFieldPath: "metadata.name"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.region"
                toFieldPath: "spec.forProvider.location"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.name"
                toFieldPath: "metadata.labels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "metadata.labels[crossplane.io/namespace]"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.nodeCount"
                toFieldPath: "spec.forProvider.defaultNodePool.nodeCount"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.nodeSku"
                toFieldPath: "spec.forProvider.defaultNodePool.vmSize"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.nodeImage"
                toFieldPath: "spec.forProvider.defaultNodePool.osSku"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.version"
                toFieldPath: "spec.forProvider.kubernetesVersion"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.networkProfile.networkPlugin"
                toFieldPath: "spec.forProvider.networkProfile.networkPlugin"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.networkProfile.networkPolicy"
                toFieldPath: "spec.forProvider.networkProfile.networkPolicy"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.networkProfile.serviceCidr"
                toFieldPath: "spec.forProvider.networkProfile.serviceCidr"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.networkProfile.dnsServiceIp"
                toFieldPath: "spec.forProvider.networkProfile.dnsServiceIp"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.name"
                toFieldPath: "spec.forProvider.nodeResourceGroup"
              - type: ToCompositeFieldPath
                fromFieldPath: "status.atConnection.kubeconfig"
                toFieldPath: "connectionDetails.KUBECONFIG"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.resourceGroup.name"
                toFieldPath: "spec.forProvider.resourceGroupNameSelector.matchLabels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "spec.forProvider.resourceGroupNameSelector.matchLabels[crossplane.io/namespace]"
              - type: CombineFromComposite
                combine:
                  variables:
                  - fromFieldPath: "spec.network.vnet.name"
                  - fromFieldPath: "spec.network.subnets[0].name"
                  strategy: string
                  string:
                    fmt: "%s-%s"
                toFieldPath: "spec.forProvider.defaultNodePool.vnetSubnetIdSelector.matchLabels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "spec.forProvider.defaultNodePool.vnetSubnetIdSelector.matchLabels[crossplane.io/namespace]"

          # 5. AKS Node Pool
          - name: aksNodePool
            base:
              apiVersion: containerservice.azure.m.upbound.io/v1beta1
              kind: KubernetesClusterNodePool
              metadata:
                name: workerpool
              spec:
                forProvider:
                  kubernetesClusterIdSelector:
                    matchControllerRef: true
                  nodeCount: 2
                  mode: User
                  tags:
                    provisioner: crossplane
                  vmSize: Standard_D2_v2
                  vnetSubnetIdSelector:
                    matchLabels:
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.name"
                toFieldPath: "metadata.labels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "metadata.labels[crossplane.io/namespace]"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.nodeCount"
                toFieldPath: "spec.forProvider.nodeCount"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aks.nodeSku"
                toFieldPath: "spec.forProvider.vmSize"
              - type: CombineFromComposite
                combine:
                  variables:
                  - fromFieldPath: "spec.network.vnet.name"
                  - fromFieldPath: "spec.network.subnets[0].name"
                  strategy: string
                  string:
                    fmt: "%s-%s"
                toFieldPath: "spec.forProvider.vnetSubnetIdSelector.matchLabels[crossplane.io/external-resource-name]"
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.namespace"
                toFieldPath: "spec.forProvider.vnetSubnetIdSelector.matchLabels[crossplane.io/namespace]"

          # 6. Azure Key Vault
          # - name: keyVault
          #   base:
          #     apiVersion: keyvault.azure.m.upbound.io/v1beta1
          #     kind: Vault
          #     spec:
          #       forProvider:
          #         location: "West Europe"
          #         resourceGroupNameSelector:
          #           matchLabels:
          #             environment: "dummy"
          #         skuName: "standard"
          #         tenantId: "ac401188-1955-4ac3-a3ff-8e6b0143b153"
          #         enabledForDeployment: true
          #         enabledForDiskEncryption: true
          #         enabledForTemplateDeployment: true
          #         enableRbacAuthorization: true
          #   patches:
          #     - type: FromCompositeFieldPath
          #       fromFieldPath: "metadata.name"
          #       toFieldPath: "metadata.name"
          #     - type: FromCompositeFieldPath
          #       fromFieldPath: "spec.region"
          #       toFieldPath: "spec.forProvider.location"
          #     - type: ToCompositeFieldPath
          #       fromFieldPath: "status.atConnection.vaultUri"
          #       toFieldPath: "connectionDetails.KEYVAULT_URI"
