apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: azure-environment-composition
spec:
  # must match your XRD apiVersion + kind
  compositeTypeRef:
    apiVersion: platform.ihk.org/v1alpha1
    kind: Environment
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        # The function will return a list of desired resources.
        resources:
          # 1. Resource Group
          - name: resourceGroup
            base:
              apiVersion: azure.m.upbound.io/v1beta1
              kind: ResourceGroup
              metadata:
                name: "rgName-placeholder"
                labels:
                  provisioner: crossplane
              spec:
                forProvider:
                  location: "West Europe"
                  tags:
                    provisioner: crossplane
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.name"
                toFieldPath: "metadata.name"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.region"
                toFieldPath: "spec.forProvider.location"

          # 2. Virtual Network
          - name: virtualNetwork
            base:
              apiVersion: network.azure.m.upbound.io/v1beta1
              kind: VirtualNetwork
              metadata:
                name: "vnetName-placeholder"
                labels:
                  provisioner: crossplane
              spec:
                forProvider:
                  addressSpace: ["10.0.0.0/16"]
                  resourceGroupNameSelector:
                    matchLabels:
                      provisioner: crossplane
                  location: "West Europe"
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.name"
                toFieldPath: "metadata.name"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.region"
                toFieldPath: "spec.forProvider.location"

          # 3. Subnet for AKS
          - name: subnetAks
            base:
              apiVersion: network.azure.m.upbound.io/v1beta1
              kind: Subnet
              metadata:
                name: aks-subnet
              spec:
                forProvider:
                  addressPrefixes: ["10.0.1.0/24"]
                  resourceGroupNameSelector:
                    matchLabels:
                      provisioner: crossplane
                  virtualNetworkNameSelector:
                    matchLabels:
                      provisioner: crossplane

          # 4. AKS Cluster
          - name: aksCluster
            base:
              apiVersion: containerservice.azure.m.upbound.io/v1beta1
              kind: KubernetesCluster
              metadata:
                name: "aksName-placeholder"
                labels:
                  provisioner: crossplane
              spec:
                forProvider:
                  defaultNodePool:
                    name: default
                    nodeCount: 1
                    vmSize: Standard_D2_v2
                    vnetSubnetIdSelector:
                      matchLabels:
                        provisioner: crossplane
                  dnsPrefix: "aks"
                  identity:
                    type: SystemAssigned
                  location: "West Europe"
                  resourceGroupNameSelector:
                    matchLabels:
                      provisioner: crossplane
                  kubernetesVersion: "1.30.0"
                  networkProfile:
                    serviceCidr: "10.0.2.0/24"
                    dnsServiceIp: "10.0.2.10"
                    networkPlugin: "azure"
                    networkPolicy: "calico"
                  tags:
                    provisioner: crossplane
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: "metadata.name"
                toFieldPath: "metadata.name"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.region"
                toFieldPath: "spec.forProvider.location"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aksNodeCount"
                toFieldPath: "spec.forProvider.defaultNodePool.nodeCount"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aksNodeSku"
                toFieldPath: "spec.forProvider.defaultNodePool.vmSize"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aksKubernetesVersion"
                toFieldPath: "spec.forProvider.kubernetesVersion"
              - type: ToCompositeFieldPath
                fromFieldPath: "status.atConnection.kubeconfig"
                toFieldPath: "connectionDetails.KUBECONFIG"

          # 5. AKS Node Pool
          - name: aksNodePool
            base:
              apiVersion: containerservice.azure.m.upbound.io/v1beta1
              kind: KubernetesClusterNodePool
              metadata:
                name: "worker"
              spec:
                forProvider:
                  kubernetesClusterIdSelector:
                    matchControllerRef: true
                  nodeCount: 1
                  tags:
                    provisioner: crossplane
                  vmSize: Standard_D2_v2
                  vnetSubnetIdSelector:
                    matchControllerRef: true
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aksNodeCount"
                toFieldPath: "spec.forProvider.nodeCount"
              - type: FromCompositeFieldPath
                fromFieldPath: "spec.aksNodeSku"
                toFieldPath: "spec.forProvider.vmSize"

          # 6. Azure Key Vault
          # - name: keyVault
          #   base:
          #     apiVersion: keyvault.azure.m.upbound.io/v1beta1
          #     kind: Vault
          #     spec:
          #       forProvider:
          #         location: "West Europe"
          #         resourceGroupNameSelector:
          #           matchLabels:
          #             environment: "dummy"
          #         skuName: "standard"
          #         tenantId: "ac401188-1955-4ac3-a3ff-8e6b0143b153"
          #         enabledForDeployment: true
          #         enabledForDiskEncryption: true
          #         enabledForTemplateDeployment: true
          #         enableRbacAuthorization: true
          #   patches:
          #     - type: FromCompositeFieldPath
          #       fromFieldPath: "metadata.name"
          #       toFieldPath: "metadata.name"
          #     - type: FromCompositeFieldPath
          #       fromFieldPath: "spec.region"
          #       toFieldPath: "spec.forProvider.location"
          #     - type: ToCompositeFieldPath
          #       fromFieldPath: "status.atConnection.vaultUri"
          #       toFieldPath: "connectionDetails.KEYVAULT_URI"
